"""Freeze the modern-TSFM benchmark run's provenance into an isolated manifest.

``docs/MODERN_TSFM_BENCHMARK.md`` requires that, before any TSFM number is cited
in the thesis, the exact package versions, model revisions, device, and output
hashes be frozen. The broad TSFM admission benchmark remains isolated from the
core requirements and runs in two separate Python-3.11 environments. The
admitted Chronos-2 counterfactual is regenerated by ``run_all.py``, which then
refreshes this deterministic provenance record before the main manifest check.

This script does not run any model and does not download weights. It only
introspects what is already installed and cached, plus the benchmark CSV outputs
already on disk. Re-run it on the same machine that produced the cited TSFM
numbers; if a venv or the HF cache is absent
the corresponding block is recorded as ``unavailable`` rather than fabricated.

Run from the repo root (core venv is fine — no model weights are touched):
    python scripts/freeze_tsfm_run.py
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
import platform
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from lngfreight import config  # noqa: E402


OUT = "data/processed/tsfm_run_manifest.json"

# The two isolated benchmark environments and the packages whose versions fix the
# numerical result (see docs/MODERN_TSFM_BENCHMARK.md "Two benchmark environments").
BENCH_ENVS = {
    ".venv-bench": (
        "chronos-forecasting", "torch", "uni2ts", "gluonts", "transformers",
        "accelerate", "numpy", "pandas",
    ),
    ".venv-timesfm": (
        "timesfm", "torch", "transformers", "huggingface-hub", "numpy", "pandas",
    ),
}
BENCH_LOCKS = {
    ".venv-bench": "requirements-benchmark.lock.txt",
    ".venv-timesfm": "requirements-timesfm.lock.txt",
}

# Model repos pulled by the adapters in src/lngfreight/tsfm.py.
MODEL_REPOS = (
    "models--amazon--chronos-2",
    "models--google--timesfm-2.5-200m-pytorch",
    "models--Salesforce--moirai-2.0-R-small",
)

# Benchmark + counterfactual-cross-check outputs whose identity is the cited
# result. The counterfactual files are the Chronos-2 ADMITTED cross-check
# (run_tsfm_counterfactual.py) and are model results, so they are frozen too.
BENCH_OUTPUTS = (
    "data/processed/tsfm_benchmark_scores.csv",
    "data/processed/tsfm_benchmark_forecasts.csv",
    "data/processed/tsfm_benchmark_summary.csv",
    "data/processed/tsfm_admission_test.csv",
    "data/processed/tsfm_counterfactual_summary.csv",
    "data/processed/tsfm_counterfactual_daily.csv",
)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _output_sha256(path: Path) -> str:
    """Hash stable CSV content, excluding wall-clock benchmark timings."""
    if path.suffix.lower() != ".csv":
        return _sha256(path)
    with path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.reader(fh))
    if not rows:
        return _sha256(path)
    keep = [
        index
        for index, name in enumerate(rows[0])
        if not name.startswith("runtime_s")
    ]
    if len(keep) == len(rows[0]):
        return _sha256(path)
    canonical = io.StringIO(newline="")
    writer = csv.writer(canonical, lineterminator="\n")
    for row in rows:
        writer.writerow([row[index] for index in keep])
    return hashlib.sha256(canonical.getvalue().encode("utf-8")).hexdigest()


def _venv_provenance(root: Path, venv: str, packages: tuple[str, ...]) -> dict:
    py = root / venv / "bin" / "python"
    if not py.exists():
        return {"status": "unavailable", "reason": f"{venv}/bin/python not found"}
    probe = (
        "import json,platform\n"
        "import pandas\n"
        "from importlib.metadata import version, PackageNotFoundError\n"
        f"pkgs={list(packages)!r}\n"
        "out={}\n"
        "for p in pkgs:\n"
        "    try: out[p]=version(p)\n"
        "    except PackageNotFoundError: out[p]='not-installed'\n"
        "info={'python':platform.python_version(),'platform':platform.platform(),"
        "'packages':out,'pandas_import_version':pandas.__version__,"
        "'pandas_metadata_version':version('pandas'),"
        "'pandas_import_path':pandas.__file__}\n"
        "print(json.dumps(info))\n"
    )
    try:
        res = subprocess.run(
            [str(py), "-c", probe], capture_output=True, text=True, check=True
        )
    except subprocess.CalledProcessError as exc:  # pragma: no cover - env probe
        return {"status": "error", "reason": exc.stderr.strip()[:500]}
    data = json.loads(res.stdout)
    check = subprocess.run(
        [str(py), "-m", "pip", "check"], capture_output=True, text=True
    )
    data["pip_check"] = "passed" if check.returncode == 0 else check.stdout.strip()
    data["metadata_consistent"] = (
        data["pandas_import_version"] == data["pandas_metadata_version"]
    )
    data["status"] = "captured"
    return data


def _environment_provenance(
    root: Path, venv: str, packages: tuple[str, ...]
) -> dict:
    data = _venv_provenance(root, venv, packages)
    lock_rel = BENCH_LOCKS[venv]
    lock_path = root / lock_rel
    data["lockfile"] = lock_rel
    data["lockfile_sha256"] = _sha256(lock_path)
    if data.get("status") != "captured":
        return data

    py = root / venv / "bin" / "python"
    freeze = subprocess.run(
        [str(py), "-m", "pip", "freeze"], capture_output=True, text=True, check=True
    )
    installed = sorted(line.strip().lower() for line in freeze.stdout.splitlines() if line)
    locked = sorted(
        line.strip().lower()
        for line in lock_path.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    )
    data["locked_distribution_count"] = len(locked)
    data["installed_distribution_count"] = len(installed)
    data["lock_matches_installed"] = locked == installed
    return data


def _model_revisions(hub: Path) -> dict:
    if not hub.exists():
        return {"status": "unavailable", "reason": f"{hub} not found"}
    revisions = {}
    for repo in MODEL_REPOS:
        snap = hub / repo / "snapshots"
        if snap.exists():
            commits = sorted(p.name for p in snap.iterdir() if p.is_dir())
            revisions[repo] = commits
        else:
            revisions[repo] = ["unavailable"]
    return {
        "status": "captured",
        "cache_scope": "default_huggingface_hub_cache",
        "snapshots": revisions,
    }


def main() -> int:
    root = config.ROOT
    hub = Path.home() / ".cache" / "huggingface" / "hub"

    outputs = {}
    for rel in BENCH_OUTPUTS:
        p = root / rel
        outputs[rel] = _output_sha256(p) if p.exists() else "missing"

    manifest = {
        "manifest_schema": 2,
        "capture_host_platform": platform.platform(),
        "note": (
            "Host-bound provenance for the isolated TSFM admission benchmark and "
            "the run_all-regenerated admitted Chronos-2 counterfactual. Re-run on "
            "the machine that produced the cited numbers; verify these versions/"
            "revisions match docs/MODERN_TSFM_BENCHMARK.md before citing any TSFM "
            "result. Foundation models are a robustness cross-check only, never "
            "the locked AR-only primary (CLAUDE.md rule 2)."
        ),
        "device": "cpu",
        "determinism_policy": {
            "seed": int(config.settings()["reproducibility"]["random_seed"]),
            "python_random_seeded": True,
            "numpy_seeded": True,
            "torch_seeded": True,
            "torch_deterministic_algorithms": True,
            "wall_clock_runtime_columns_excluded_from_output_hashes": True,
        },
        "benchmark_output_hash_policy": (
            "raw SHA-256 except benchmark CSV runtime_s* columns, which are "
            "excluded as nondeterministic wall-clock diagnostics"
        ),
        "benchmark_environments": {
            venv: _environment_provenance(root, venv, pkgs)
            for venv, pkgs in BENCH_ENVS.items()
        },
        "model_revisions": _model_revisions(hub),
        "benchmark_output_sha256": outputs,
    }

    path = root / OUT
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path}")
    for venv, prov in manifest["benchmark_environments"].items():
        if prov.get("status") == "captured":
            torch_v = prov["packages"].get("torch", "n/a")
            print(
                f"  {venv}: python {prov['python']}, torch {torch_v}, "
                f"pandas metadata consistent={prov['metadata_consistent']}, "
                f"pip check={prov['pip_check']}, "
                f"lock exact={prov['lock_matches_installed']}"
            )
        else:
            print(f"  {venv}: {prov['status']} ({prov.get('reason', '')})")
    rev = manifest["model_revisions"]
    if rev.get("status") == "captured":
        for repo, commits in rev["snapshots"].items():
            print(f"  {repo}: {','.join(commits)}")
    missing = [k for k, v in outputs.items() if v == "missing"]
    if missing:
        print(f"  WARNING: missing benchmark outputs: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
