"""Freeze raw-data hashes and write a reproducibility/run manifest.

Raw source files stay out of Git; `data/raw/SHA256SUMS` is the tracked identity
of the exact snapshots used. Processed artifacts and reports are versioned.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import tempfile
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from lngfreight import config  # noqa: E402
from lngfreight.specification import working_specification  # noqa: E402


RAW_HASH_FILE = "data/raw/SHA256SUMS"
VESSEL_HASH_FILE = "data/raw/SHA256SUMS.vessel"
SENSITIVITY_HASH_FILE = "data/raw/SHA256SUMS.sensitivity"
RUN_MANIFEST = "data/processed/reproducibility_manifest.json"
CONFIG_INPUTS = (
    "config/settings.yaml",
    "config/sources.yaml",
    "config/provenance_path_migrations.json",
    "config/provenance_source_payload_exceptions.json",
)
INTERIM_INPUTS = (
    "data/interim/gem_lng_carriers.json",
)

# Exact deterministic outputs regenerated by scripts/run_all.py. The broad TSFM
# admission benchmark remains host-bound, but the admitted Chronos-2
# counterfactual consumed by the report and its deterministic provenance
# manifest are included here.
ORCHESTRATED_ARTIFACTS = (
    "data/interim/global_lng_carrier_frame.csv",
    "data/interim/panel_free.csv",
    "data/processed/ais_dark_bound_critical_rates.csv",
    "data/processed/ais_dark_bound_sensitivity.csv",
    "data/processed/alignment_audit.csv",
    "data/processed/baseline_forecasts.csv",
    "data/processed/baseline_scores.csv",
    "data/processed/baseline_summary.csv",
    "data/processed/basin_exposure_summary.csv",
    "data/processed/block_conformal_summary.csv",
    "data/processed/block_placebo_effects.csv",
    "data/processed/bsts_counterfactual_daily.csv",
    "data/processed/bsts_counterfactual_summary.csv",
    "data/processed/bsts_pre_period_ppc.csv",
    "data/processed/bsts_pre_period_ppc_summary.json",
    "data/processed/bsts_prior_sensitivity.csv",
    "data/processed/bsts_validation_forecasts.csv",
    "data/processed/bsts_validation_scores.csv",
    "data/processed/candidate_voyage_endpoints.csv",
    "data/processed/capacity_missingness_diagnostics.csv",
    "data/processed/counterfactual_intervals_daily.csv",
    "data/processed/counterfactual_intervals_summary.csv",
    "data/processed/counterfactual_post_treatment.csv",
    "data/processed/counterfactual_post_treatment_summary.csv",
    "data/processed/global_candidate_voyage_endpoints.csv",
    "data/processed/global_carrier_frame_diagnostics.json",
    "data/processed/global_lng_terminal_matching_audit.csv",
    "data/processed/global_voyage_feasibility_summary.json",
    "data/processed/gulf_departure_wto_validation_by_terminal.csv",
    "data/processed/gulf_departure_wto_validation_correlations.csv",
    "data/processed/gulf_departure_wto_validation_daily.csv",
    "data/processed/gulf_departure_wto_validation_summary.json",
    "data/processed/gulf_departure_wto_validation_weekly.csv",
    "data/processed/importer_basin_exposure_diagnostics.json",
    "data/processed/importer_exposure_summary.csv",
    "data/processed/importer_exposure_voyages.csv",
    "data/processed/importer_outcomes.csv",
    "data/processed/importer_outcomes_summary.json",
    "data/processed/lng_rewiring_monthly_metrics.csv",
    "data/processed/lng_rewiring_network.csv",
    "data/processed/lng_rewiring_graph_metrics.csv",
    "data/processed/lng_rewiring_summary.csv",
    "data/processed/lng_network_anomaly_monthly.csv",
    "data/processed/lng_network_anomaly_summary.csv",
    "data/processed/lng_resilience_typology.csv",
    "data/processed/lng_rewiring_post_month_sensitivity.csv",
    "data/processed/lng_typology_threshold_sensitivity.csv",
    "data/processed/lng_reallocation_basin_demands.csv",
    "data/processed/lng_reallocation_cost_matrix.csv",
    "data/processed/lng_reallocation_solution.csv",
    "data/processed/lng_reallocation_summary.csv",
    "data/processed/lng_reallocation_supply_nodes.csv",
    "data/processed/inferred_capacity_nautical_miles_comparison.csv",
    "data/processed/inferred_capacity_nautical_miles_bootstrap.json",
    "data/processed/inferred_capacity_nautical_miles_decomposition.json",
    "data/processed/inferred_capacity_nautical_miles_diagnostics.json",
    "data/processed/inferred_capacity_nautical_miles_period_summary.csv",
    "data/processed/inferred_capacity_nautical_miles_voyages.csv",
    "data/processed/lng_index_counterfactual_daily.csv",
    "data/processed/lng_index_counterfactual_summary.csv",
    "data/processed/lng_terminal_matching_audit.csv",
    "data/processed/long_horizon_intervals_summary.csv",
    "data/processed/maritime_route_distance_summary.json",
    "data/processed/maritime_route_distances.csv",
    "data/processed/maritime_route_distances_sensitivity.csv",
    "data/processed/mechanism_evidence_summary.csv",
    "data/processed/model_information_sets.csv",
    "data/processed/model_input_coverage.csv",
    "data/processed/panel_aligned.csv",
    "data/processed/placebo_time_effects.csv",
    "data/processed/placebo_time_summary.csv",
    "data/processed/provenance_audit_summary.json",
    "data/processed/raw_provenance_inventory.csv",
    "data/processed/run_spec_comparison.csv",
    "data/processed/romano_wolf_stepdown.csv",
    "data/processed/spatial_placebo_effects.csv",
    "data/processed/spatial_placebo_leave_one_out.csv",
    "data/processed/spatial_placebo_summary.csv",
    "data/processed/synthetic_control_daily.csv",
    "data/processed/synthetic_control_prefit_sensitivity.csv",
    "data/processed/synthetic_control_scales.csv",
    "data/processed/synthetic_control_summary.csv",
    "data/processed/synthetic_control_weights.csv",
    "data/processed/synthetic_donor_pool_stress.csv",
    "data/processed/synthetic_donor_time_block_maxima.csv",
    "data/processed/synthetic_donor_time_inference.csv",
    "data/processed/synthetic_donor_time_placebos.csv",
    "data/processed/treatment_robustness_daily.csv",
    "data/processed/treatment_robustness_summary.csv",
    "data/processed/tsfm_counterfactual_daily.csv",
    "data/processed/tsfm_counterfactual_summary.csv",
    "data/processed/tsfm_run_manifest.json",
    "data/processed/vessel_data_feasibility.json",
    "data/processed/vessel_day_comparison.csv",
    "data/processed/vessel_day_diagnostics.json",
    "data/processed/vessel_day_period_summary.csv",
    "data/processed/vessel_day_voyage_diagnostics.csv",
    "data/processed/voyage_feasibility_summary.json",
    "reports/current_results_summary.md",
    "reports/figures/bsts_counterfactual.png",
    "reports/figures/bsts_pre_period_ppc.png",
    "reports/figures/fig1_chokepoint_event_study.pdf",
    "reports/figures/fig1_chokepoint_event_study.png",
    "reports/figures/fig2_hormuz_robustness.pdf",
    "reports/figures/fig2_hormuz_robustness.png",
    "reports/figures/fig3_energy_response.pdf",
    "reports/figures/fig3_energy_response.png",
    "reports/figures/fig4_missingness_map.pdf",
    "reports/figures/fig4_missingness_map.png",
    "reports/figures/lng_index_counterfactual.png",
    "reports/figures/mechanism_evidence_summary.pdf",
    "reports/figures/mechanism_evidence_summary.png",
    "reports/figures/network_rewiring_gulf_vs_total.pdf",
    "reports/figures/network_rewiring_gulf_vs_total.png",
    "reports/figures/network_rewiring_origin_composition.pdf",
    "reports/figures/network_rewiring_origin_composition.png",
    "reports/figures/network_rewiring_source_structure.pdf",
    "reports/figures/network_rewiring_source_structure.png",
    "reports/figures/run_actual_vs_counterfactual.png",
    "reports/figures/run_placebo_distribution.png",
    "reports/figures/run_synthetic_control_placebo_paths.png",
    "reports/figures/run_synthetic_control_path.png",
    "reports/mechanism_results_summary.md",
    "reports/network_rewiring_summary.md",
    "reports/run_output.md",
)

# The raw inputs the frozen PortWatch pipeline (scripts/run_all.py) actually
# consumes. The raw-hash check is scoped to THESE so the core run self-verifies
# independently of the optional Phase-3A vessel branch (CURRENT_PLAN.md branch
# isolation). Vessel-branch raw inputs are frozen separately in SHA256SUMS.vessel.
CORE_RAW_INPUTS = (
    "data/raw/eia/brent_spot__PET_RBRTE_D.csv",
    "data/raw/eia/henry_hub_spot__NG_RNGWHHD_D.csv",
    "data/raw/portwatch/Daily_Chokepoints_Data.csv",
    "data/raw/portwatch/hormuz_tanker_capacity__chokepoint_strait_of_hormuz_capacity_tanker.csv",
    "data/raw/portwatch/hormuz_tanker_transits__chokepoint_strait_of_hormuz_n_tanker__6631382171dc.csv",
    "data/raw/portwatch/panama_tanker_capacity__chokepoint_panama_canal_capacity_tanker.csv",
    "data/raw/portwatch/panama_tanker_transits__chokepoint_panama_canal_n_tanker.csv",
    "data/raw/wto_hormuz/voy_intake_index_lng_export.csv",
)

# Frozen inputs used only by explicitly labelled sensitivity branches. Keeping
# this scope separate prevents a candidate vintage from being mistaken for the
# pinned primary or disappearing inside the broad vessel/open-data inventory.
SENSITIVITY_RAW_INPUTS = (
    "data/raw/portwatch/vintages/"
    "Daily_Chokepoints_Data__vintage_2026-08-09.csv",
)

# Historical vintages preserved for audit but excluded from all active input
# scopes. See docs/PORTWATCH_VINTAGE_REGISTER.md.
QUARANTINED_RAW_INPUTS = (
    "data/raw/portwatch/hormuz_tanker_transits__chokepoint_strait_of_hormuz_n_tanker.csv",
    "data/raw/portwatch/quarantined_panama_tanker_capacity_duplicate__chokepoint_panama_canal_capacity_tanker.csv",
)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def raw_hashes(root: Path) -> dict[str, str]:
    raw_dir = root / "data" / "raw"
    ignored = {
        raw_dir / "SHA256SUMS",
        raw_dir / "SHA256SUMS.sensitivity",
        raw_dir / "SHA256SUMS.vessel",
        raw_dir / "provenance.jsonl",
        raw_dir / ".gitkeep",
    }
    return {
        path.relative_to(root).as_posix(): sha256_file(path)
        for path in sorted(raw_dir.rglob("*"))
        if path.is_file() and path not in ignored
    }


def core_raw_hashes(root: Path) -> dict[str, str]:
    """Hashes of the core PortWatch inputs the frozen pipeline consumes.

    Fails loudly if a declared core input is missing, so a renamed or deleted
    core snapshot cannot silently pass the check (CLAUDE.md rule 1).
    """
    out: dict[str, str] = {}
    for rel in CORE_RAW_INPUTS:
        path = root / rel
        if not path.is_file():
            raise FileNotFoundError(f"core raw input missing: {rel}")
        out[rel] = sha256_file(path)
    return out


def sensitivity_raw_hashes(root: Path) -> dict[str, str]:
    """Hashes of declared sensitivity-only inputs; missing files fail loudly."""
    return _declared_hashes(root, SENSITIVITY_RAW_INPUTS, "sensitivity input")


def vessel_raw_hashes(root: Path) -> dict[str, str]:
    """Hashes of vessel-branch raw inputs: everything under data/raw that is not a
    core input or a transient download archive (.zip). OS junk files (.DS_Store,
    Finder metadata) are excluded: macOS recreates them on browse, they carry no
    data, and they must never break the input-hash gate.

    The provenance-limited Bloomberg payloads under data/raw/bloomberg_transcription/
    are excluded too: they exist only on machines where the opt-in
    ENABLE_BLOOMBERG_LAYER branch has run, so sweeping them here would break the
    default free-data check everywhere else. They are pinned instead by
    config/bloomberg_exports.yaml (workbook checksums, verified on every load)
    and scripts/freeze_bloomberg_layer.py (payload snapshots), which run inside
    the branch that guarantees the files exist."""
    core = set(CORE_RAW_INPUTS)
    sensitivity = set(SENSITIVITY_RAW_INPUTS)
    quarantined = set(QUARANTINED_RAW_INPUTS)
    return {
        rel: digest
        for rel, digest in raw_hashes(root).items()
        if rel not in core
        and rel not in sensitivity
        and rel not in quarantined
        and not rel.startswith("data/raw/bloomberg_transcription/")
        and not rel.endswith(".zip")
        and Path(rel).name != ".DS_Store"
        and not Path(rel).name.startswith("._")
    }


def interim_input_hashes(root: Path) -> dict[str, str]:
    return _declared_hashes(root, INTERIM_INPUTS, "interim input")


def _declared_hashes(
    root: Path, relative_paths: tuple[str, ...], label: str
) -> dict[str, str]:
    out = {}
    for rel in relative_paths:
        path = root / rel
        if not path.is_file():
            raise FileNotFoundError(f"{label} missing: {rel}")
        out[rel] = sha256_file(path)
    return out


def _artifact_hashes(root: Path) -> dict[str, str]:
    return _declared_hashes(root, ORCHESTRATED_ARTIFACTS, "orchestrated artifact")


def _package_versions() -> dict[str, str]:
    out = {}
    for package in (
        "matplotlib", "numpy", "pandas", "pytest", "requests", "PyYAML", "searoute"
    ):
        try:
            out[package] = version(package)
        except PackageNotFoundError:
            out[package] = "not-installed"
    return out


def _write_raw_hashes(root: Path, hashes: dict[str, str], rel: str = RAW_HASH_FILE) -> None:
    path = root / rel
    text = "".join(f"{digest}  {name}\n" for name, digest in hashes.items())
    path.write_text(text, encoding="utf-8")


def _read_hash_file(root: Path, relative_path: str) -> dict[str, str]:
    path = root / relative_path
    if not path.exists():
        return {}
    rows = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        digest, name = line.split("  ", 1)
        rows[name] = digest
    return rows


def _working_specification() -> dict[str, object]:
    spec = working_specification()
    return {
        "status": spec.status,
        "branch": spec.branch,
        "primary_outcome": spec.primary_outcome,
        "robustness_outcome": spec.robustness_outcome,
        "active_secondary_outcomes": list(spec.active_secondary_outcomes),
        "dormant_secondary_outcomes": list(spec.dormant_secondary_outcomes),
        "primary_estimator": spec.primary_estimator,
        "benchmark_estimators": list(spec.benchmark_estimators),
        "conditional_sensitivity_estimators": list(
            spec.conditional_sensitivity_estimators
        ),
        "reporting_term": spec.reporting_term,
        "transformer_enabled": spec.transformer_enabled,
    }


def build_manifest(root: Path) -> dict[str, object]:
    return {
        "manifest_schema": 2,
        "artifact_scope": "deterministic_outputs_regenerated_by_scripts/run_all.py",
        "excluded_artifact_families": [
            "broad isolated TSFM admission weight-run tables "
            "(data/processed/tsfm_benchmark_* and tsfm_admission_test.csv); "
            "their stable identities are pinned inside the included "
            "tsfm_run_manifest.json, excluding wall-clock runtime columns",
            "credential-gated Spark access report",
            "manually assembled supervisor presentation assets",
            "full run transcript (reports/reproducibility_run_transcript.txt); "
            "retained for audit but excluded from byte-deterministic identity "
            "because subprocess/test timing text is wall-clock dependent",
            "exploratory corridor-transmission outputs not regenerated by "
            "scripts/run_all.py (data/processed/corridor_transmission_*, "
            "data/processed/transmission_chain_cascade.csv); version-controlled "
            "but outside the deterministic-regeneration guarantee",
            "exploratory donor-contamination stress outputs "
            "(data/processed/donor_contamination_*); version-controlled, "
            "not run_all-regenerated",
            "Phase-3B basin-interval simulation outputs "
            "(data/processed/basin_interval_coverage_*); unused-fallback "
            "scenario simulation, version-controlled, not run_all-regenerated",
        ],
        "python": platform.python_version(),
        "platform": platform.platform(),
        "packages": _package_versions(),
        "working_specification": _working_specification(),
        "config_sha256": _declared_hashes(root, CONFIG_INPUTS, "config input"),
        "raw_sha256": core_raw_hashes(root),
        "vessel_raw_sha256": vessel_raw_hashes(root),
        "interim_input_sha256": interim_input_hashes(root),
        "artifact_sha256": _artifact_hashes(root),
        "test_command": ".venv/bin/python -m pytest -q",
    }


def _print_drift(expected: dict[str, object], actual: dict[str, object]) -> None:
    expected_artifacts = expected.get("artifact_sha256", {})
    actual_artifacts = actual.get("artifact_sha256", {})
    if isinstance(expected_artifacts, dict) and isinstance(actual_artifacts, dict):
        missing = sorted(set(expected_artifacts) - set(actual_artifacts))
        extra = sorted(set(actual_artifacts) - set(expected_artifacts))
        changed = sorted(
            key
            for key in set(expected_artifacts) & set(actual_artifacts)
            if expected_artifacts[key] != actual_artifacts[key]
        )
        for label, paths in (("missing", missing), ("unexpected", extra), ("changed", changed)):
            for path in paths:
                print(f"  artifact {label}: {path}")
    for section in (
        "manifest_schema", "artifact_scope", "excluded_artifact_families",
        "python", "platform", "packages", "working_specification",
        "config_sha256", "raw_sha256", "vessel_raw_sha256",
        "interim_input_sha256", "test_command",
    ):
        if expected.get(section) != actual.get(section):
            print(f"  metadata changed: {section}")


def verify_manifest(root: Path) -> int:
    committed_path = root / RUN_MANIFEST
    if not committed_path.is_file():
        print(f"ARTIFACT VERIFICATION FAILED: missing {RUN_MANIFEST}")
        return 1
    expected = json.loads(committed_path.read_text(encoding="utf-8"))
    actual = build_manifest(root)
    with tempfile.TemporaryDirectory(prefix="lngfreight-manifest-") as temp_dir:
        candidate_path = Path(temp_dir) / "reproducibility_manifest.json"
        candidate_path.write_text(
            json.dumps(actual, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        candidate = json.loads(candidate_path.read_text(encoding="utf-8"))
    if expected != candidate:
        print("ARTIFACT VERIFICATION FAILED: regenerated outputs drift from committed manifest.")
        _print_drift(expected, candidate)
        return 1
    print(
        "ARTIFACT VERIFICATION PASSED: "
        f"{len(actual['artifact_sha256'])} regenerated artifacts match."
    )
    return 0


def check_inputs(root: Path) -> int:
    checks = (
        ("core raw", _read_hash_file(root, RAW_HASH_FILE), core_raw_hashes(root)),
        ("vessel raw", _read_hash_file(root, VESSEL_HASH_FILE), vessel_raw_hashes(root)),
    )
    failed = False
    for label, frozen, current in checks:
        if frozen != current:
            print(f"INPUT HASH CHECK FAILED: {label} snapshots differ.")
            failed = True
        else:
            print(f"INPUT HASH CHECK PASSED: {len(current)} {label} files match.")
    manifest_path = root / RUN_MANIFEST
    if manifest_path.is_file():
        frozen_interim = json.loads(manifest_path.read_text()).get(
            "interim_input_sha256", {}
        )
        current_interim = interim_input_hashes(root)
        if frozen_interim != current_interim:
            print("INPUT HASH CHECK FAILED: frozen interim inputs differ.")
            failed = True
        else:
            print(
                f"INPUT HASH CHECK PASSED: {len(current_interim)} interim inputs match."
            )
    return int(failed)


def refresh_input_hashes(root: Path) -> None:
    current_raw = core_raw_hashes(root)
    vessel_raw = vessel_raw_hashes(root)
    _write_raw_hashes(root, current_raw)
    _write_raw_hashes(root, vessel_raw, rel=VESSEL_HASH_FILE)
    print(f"wrote {root / RAW_HASH_FILE} ({len(current_raw)} core raw files)")
    print(f"wrote {root / VESSEL_HASH_FILE} ({len(vessel_raw)} vessel raw files)")


def main(
    check: bool = False,
    verify: bool = False,
    refresh_inputs: bool = False,
) -> int:
    root = config.ROOT
    if check:
        return check_inputs(root)
    if verify:
        return verify_manifest(root)
    if refresh_inputs:
        refresh_input_hashes(root)
        return 0

    refresh_input_hashes(root)
    manifest = build_manifest(root)
    path = root / RUN_MANIFEST
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(manifest['artifact_sha256'])} artifacts)")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify frozen input hashes")
    mode.add_argument(
        "--verify", action="store_true",
        help="compare regenerated artifacts with the committed manifest",
    )
    mode.add_argument(
        "--refresh-inputs",
        action="store_true",
        help="deliberately refresh raw-input hash files without changing the run manifest",
    )
    args = parser.parse_args()
    raise SystemExit(
        main(
            check=args.check,
            verify=args.verify,
            refresh_inputs=args.refresh_inputs,
        )
    )
